#!/bin/sh

while true; do
  #su-exec $UID:$GID
  php -d memory_limit=<CRON_MEMORY_LIMIT> -f /nextcloud/occ preview:pre-generate
  php -d memory_limit=<CRON_MEMORY_LIMIT> -f /nextcloud/cron.php
  sleep <CRON_PERIOD>
done
